import { Subject, Chapter } from '../types';

export const mockSubjects: Subject[] = [
  {
    id: '1',
    name: 'Analyse',
    slug: 'analyse',
    description: 'Fonctions, limites, dérivées et intégrales',
    chaptersCount: 12,
    progress: 45,
    icon: 'TrendingUp',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    id: '2',
    name: 'Algèbre',
    slug: 'algebre',
    description: 'Équations, systèmes et structures algébriques',
    chaptersCount: 10,
    progress: 60,
    icon: 'Variable',
    color: 'from-purple-500 to-pink-500',
  },
  {
    id: '3',
    name: 'Trigonométrie',
    slug: 'trigonometrie',
    description: 'Fonctions trigonométriques et applications',
    chaptersCount: 8,
    progress: 30,
    icon: 'Triangle',
    color: 'from-green-500 to-emerald-500',
  },
  {
    id: '4',
    name: 'Géométrie',
    slug: 'geometrie',
    description: 'Géométrie plane et dans l\'espace',
    chaptersCount: 9,
    progress: 20,
    icon: 'Shapes',
    color: 'from-orange-500 to-red-500',
  },
  {
    id: '5',
    name: 'Statistique',
    slug: 'statistique',
    description: 'Probabilités et statistiques descriptives',
    chaptersCount: 7,
    progress: 75,
    icon: 'BarChart3',
    color: 'from-indigo-500 to-blue-500',
  },
  {
    id: '6',
    name: 'Physique',
    slug: 'physique',
    description: 'Mécanique, électricité et ondes',
    chaptersCount: 15,
    progress: 40,
    icon: 'Atom',
    color: 'from-teal-500 to-cyan-500',
  },
  {
    id: '7',
    name: 'Chimie',
    slug: 'chimie',
    description: 'Chimie générale, organique et inorganique',
    chaptersCount: 11,
    progress: 55,
    icon: 'FlaskConical',
    color: 'from-yellow-500 to-orange-500',
  },
  {
    id: '8',
    name: 'Biologie / Écologie',
    slug: 'biologie-ecologie',
    description: 'Biologie cellulaire, génétique et écosystèmes',
    chaptersCount: 13,
    progress: 35,
    icon: 'Leaf',
    color: 'from-green-500 to-lime-500',
  },
  {
    id: '9',
    name: 'Géographie économique',
    slug: 'geographie-economique',
    description: 'Ressources, développement et territoires',
    chaptersCount: 10,
    progress: 50,
    icon: 'Globe',
    color: 'from-blue-500 to-indigo-500',
  },
];

export const mockChapters: Record<string, Chapter[]> = {
  '1': [
    {
      id: 'c1-1',
      subjectId: '1',
      title: 'Introduction aux fonctions',
      order: 1,
      status: 'completed',
      estimatedTime: 45,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
    {
      id: 'c1-2',
      subjectId: '1',
      title: 'Limites et continuité',
      order: 2,
      status: 'in-progress',
      estimatedTime: 60,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
    {
      id: 'c1-3',
      subjectId: '1',
      title: 'Dérivées et applications',
      order: 3,
      status: 'not-started',
      estimatedTime: 90,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
    {
      id: 'c1-4',
      subjectId: '1',
      title: 'Étude de fonctions',
      order: 4,
      status: 'not-started',
      estimatedTime: 75,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
  ],
  '2': [
    {
      id: 'c2-1',
      subjectId: '2',
      title: 'Équations du premier degré',
      order: 1,
      status: 'completed',
      estimatedTime: 40,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
    {
      id: 'c2-2',
      subjectId: '2',
      title: 'Équations du second degré',
      order: 2,
      status: 'completed',
      estimatedTime: 50,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
    {
      id: 'c2-3',
      subjectId: '2',
      title: 'Systèmes d\'équations',
      order: 3,
      status: 'in-progress',
      estimatedTime: 60,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
  ],
  '3': [
    {
      id: 'c3-1',
      subjectId: '3',
      title: 'Cercle trigonométrique',
      order: 1,
      status: 'completed',
      estimatedTime: 45,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
    {
      id: 'c3-2',
      subjectId: '3',
      title: 'Fonctions sinus et cosinus',
      order: 2,
      status: 'not-started',
      estimatedTime: 55,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
  ],
  '6': [
    {
      id: 'c6-1',
      subjectId: '6',
      title: 'Cinématique',
      order: 1,
      status: 'completed',
      estimatedTime: 50,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
    {
      id: 'c6-2',
      subjectId: '6',
      title: 'Dynamique',
      order: 2,
      status: 'in-progress',
      estimatedTime: 65,
      hasQuiz: true,
      hasCourse: true,
      hasExercises: true,
    },
  ],
};
